// <auto-generated />
using System;
using HoneyBack.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HoneyBack.Migrations
{
    [DbContext(typeof(HoneyBalanceDbContext))]
    partial class HoneyBalanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HoneyBack.Models.CategoriasTransaccione", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoriaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<bool?>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Color")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#FFD8A9");

                    b.Property<bool?>("EsSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("CategoriaId")
                        .HasName("PK__Categori__F353C1C548B5BF7B");

                    b.HasIndex(new[] { "Tipo" }, "IDX_Categorias_Tipo");

                    b.HasIndex(new[] { "UsuarioId" }, "IDX_Categorias_Usuario");

                    b.HasIndex(new[] { "Nombre", "UsuarioId", "Tipo" }, "UQ_Categoria_Usuario")
                        .IsUnique()
                        .HasFilter("[UsuarioID] IS NOT NULL");

                    b.ToTable("CategoriasTransacciones");
                });

            modelBuilder.Entity("HoneyBack.Models.ConfiguracionesUsuario", b =>
                {
                    b.Property<int>("ConfiguracionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConfiguracionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfiguracionId"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AvatarURL");

                    b.Property<string>("ConfiguracionPersonalizada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("EsVeterano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FormatoFecha")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("DD/MM/YYYY");

                    b.Property<string>("Idioma")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("es");

                    b.Property<string>("MonedaPreferida")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("COP");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("NotificacionesEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("NotificacionesPush")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("PrimeraVez")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Tema")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("dark");

                    b.Property<string>("Timezone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("America/Bogota");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("ConfiguracionId")
                        .HasName("PK__Configur__9B95E0564150AC51");

                    b.HasIndex(new[] { "UsuarioId" }, "IDX_Configuraciones_Usuario");

                    b.HasIndex(new[] { "UsuarioId" }, "UQ__Configur__2B3DE7994E97C4E8")
                        .IsUnique();

                    b.ToTable("ConfiguracionesUsuario", (string)null);
                });

            modelBuilder.Entity("HoneyBack.Models.EstadisticasMensuale", b =>
                {
                    b.Property<int>("EstadisticaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EstadisticaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadisticaId"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<decimal?>("Balance")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(16, 2)")
                        .HasComputedColumnSql("([TotalIngresos]-[TotalGastos])", true);

                    b.Property<int?>("CategoriaMayorGastoId")
                        .HasColumnType("int")
                        .HasColumnName("CategoriaMayorGastoID");

                    b.Property<DateTime?>("FechaCalculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<decimal?>("MontoMayorGasto")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<int?>("NumTransacciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("TotalGastos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("TotalIngresos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("EstadisticaId")
                        .HasName("PK__Estadist__5E78B5EC289011CE");

                    b.HasIndex("CategoriaMayorGastoId");

                    b.HasIndex(new[] { "UsuarioId", "Anio", "Mes" }, "IDX_Estadisticas_Usuario_Periodo")
                        .IsDescending(false, true, true);

                    b.HasIndex(new[] { "UsuarioId", "Anio", "Mes" }, "UQ_Periodo_Usuario")
                        .IsUnique();

                    b.ToTable("EstadisticasMensuales");
                });

            modelBuilder.Entity("HoneyBack.Models.MensajesContacto", b =>
                {
                    b.Property<int>("ContactoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ContactoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactoId"));

                    b.Property<string>("Asunto")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaLeido")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("datetime");

                    b.Property<bool?>("Leido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Respuesta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("ContactoId")
                        .HasName("PK__Mensajes__8E0F85C84F21B9E0");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MensajesContacto", (string)null);
                });

            modelBuilder.Entity("HoneyBack.Models.MetasAhorro", b =>
                {
                    b.Property<int>("MetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MetaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetaId"));

                    b.Property<bool?>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("otro");

                    b.Property<string>("Color")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#FFD8A9");

                    b.Property<bool?>("Completada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCompletada")
                        .HasColumnType("datetime");

                    b.Property<DateOnly>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<DateOnly?>("FechaObjetivo")
                        .HasColumnType("date");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("MontoActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("MontoObjetivo")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Prioridad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("MetaId")
                        .HasName("PK__MetasAho__60EE57F83C03D1E5");

                    b.HasIndex(new[] { "Activa" }, "IDX_Metas_Activa");

                    b.HasIndex(new[] { "Prioridad" }, "IDX_Metas_Prioridad")
                        .IsDescending();

                    b.HasIndex(new[] { "UsuarioId" }, "IDX_Metas_Usuario");

                    b.ToTable("MetasAhorro", (string)null);
                });

            modelBuilder.Entity("HoneyBack.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TokenID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)")
                        .IsFixedLength();

                    b.Property<bool>("Used")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("TokenId")
                        .HasName("PK_PasswordResetTokens");

                    b.HasIndex(new[] { "UsuarioId", "Used", "ExpiresAtUtc" }, "IDX_PasswordResetTokens_Active");

                    b.HasIndex(new[] { "Token" }, "IDX_PasswordResetTokens_Token");

                    b.HasIndex(new[] { "UsuarioId" }, "IDX_PasswordResetTokens_Usuario");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("HoneyBack.Models.Reporte", b =>
                {
                    b.Property<int>("ReporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReporteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReporteId"));

                    b.Property<string>("ArchivoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ArchivoURL");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaGeneracion")
                        .HasColumnType("datetime");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Parametros")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoReporte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("ReporteId")
                        .HasName("PK__Reportes__0B29EA4E01DDEDB4");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("HoneyBack.Models.Sesione", b =>
                {
                    b.Property<long>("SesionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SesionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SesionId"));

                    b.Property<bool?>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("IPAddress");

                    b.Property<string>("TokenSesion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("SesionId")
                        .HasName("PK__Sesiones__52FD7C0689AF3185");

                    b.HasIndex("UsuarioId");

                    b.HasIndex(new[] { "TokenSesion" }, "UQ__Sesiones__567B1115B8F65C64")
                        .IsUnique();

                    b.ToTable("Sesiones");
                });

            modelBuilder.Entity("HoneyBack.Models.Template", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TemplateID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("CategoriaID");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaUltimoUso")
                        .HasColumnType("datetime");

                    b.Property<int?>("FrecuenciaUso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("TemplateId")
                        .HasName("PK__Template__F87ADD07FF1A0B47");

                    b.HasIndex("CategoriaId");

                    b.HasIndex(new[] { "Activo" }, "IDX_Templates_Activo");

                    b.HasIndex(new[] { "FrecuenciaUso" }, "IDX_Templates_Frecuencia")
                        .IsDescending();

                    b.HasIndex(new[] { "UsuarioId" }, "IDX_Templates_Usuario");

                    b.HasIndex(new[] { "UsuarioId", "Nombre" }, "UQ_Template_Nombre_Usuario")
                        .IsUnique();

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("HoneyBack.Models.Transaccione", b =>
                {
                    b.Property<int>("TransaccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TransaccionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransaccionId"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("TransaccionId")
                        .HasName("PK_Transacciones");

                    b.HasIndex(new[] { "Fecha" }, "IDX_Transacciones_Fecha");

                    b.HasIndex(new[] { "Tipo" }, "IDX_Transacciones_Tipo");

                    b.HasIndex(new[] { "UsuarioId" }, "IDX_Transacciones_Usuario");

                    b.ToTable("Transacciones", (string)null);
                });

            modelBuilder.Entity("HoneyBack.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AvatarURL");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PreferenciasMoneda")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("COP");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UsuarioId")
                        .HasName("PK__Usuarios__2B3DE7981B407AB9");

                    b.HasIndex(new[] { "Email" }, "UQ__Usuarios__A9D10534C1437617")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("HoneyBack.Models.CategoriasTransaccione", b =>
                {
                    b.HasOne("HoneyBack.Models.Usuario", "Usuario")
                        .WithMany("CategoriasTransacciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Categorias_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HoneyBack.Models.ConfiguracionesUsuario", b =>
                {
                    b.HasOne("HoneyBack.Models.Usuario", "Usuario")
                        .WithOne("ConfiguracionesUsuario")
                        .HasForeignKey("HoneyBack.Models.ConfiguracionesUsuario", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Configuraciones_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HoneyBack.Models.EstadisticasMensuale", b =>
                {
                    b.HasOne("HoneyBack.Models.CategoriasTransaccione", "CategoriaMayorGasto")
                        .WithMany("EstadisticasMensuales")
                        .HasForeignKey("CategoriaMayorGastoId")
                        .HasConstraintName("FK_Estadisticas_Categorias");

                    b.HasOne("HoneyBack.Models.Usuario", "Usuario")
                        .WithMany("EstadisticasMensuales")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Estadisticas_Usuarios");

                    b.Navigation("CategoriaMayorGasto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HoneyBack.Models.MensajesContacto", b =>
                {
                    b.HasOne("HoneyBack.Models.Usuario", "Usuario")
                        .WithMany("MensajesContactos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_MensajesContacto_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HoneyBack.Models.MetasAhorro", b =>
                {
                    b.HasOne("HoneyBack.Models.Usuario", "Usuario")
                        .WithMany("MetasAhorros")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Metas_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HoneyBack.Models.PasswordResetToken", b =>
                {
                    b.HasOne("HoneyBack.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PasswordResetTokens_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HoneyBack.Models.Reporte", b =>
                {
                    b.HasOne("HoneyBack.Models.Usuario", "Usuario")
                        .WithMany("Reportes")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK_Reportes_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HoneyBack.Models.Sesione", b =>
                {
                    b.HasOne("HoneyBack.Models.Usuario", "Usuario")
                        .WithMany("Sesiones")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Sesiones_UsuarioID");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HoneyBack.Models.Template", b =>
                {
                    b.HasOne("HoneyBack.Models.CategoriasTransaccione", "Categoria")
                        .WithMany("Templates")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK_Templates_Categorias");

                    b.HasOne("HoneyBack.Models.Usuario", "Usuario")
                        .WithMany("Templates")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Templates_Usuarios");

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HoneyBack.Models.Transaccione", b =>
                {
                    b.HasOne("HoneyBack.Models.Usuario", "Usuario")
                        .WithMany("Transacciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Transacciones_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HoneyBack.Models.CategoriasTransaccione", b =>
                {
                    b.Navigation("EstadisticasMensuales");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("HoneyBack.Models.Usuario", b =>
                {
                    b.Navigation("CategoriasTransacciones");

                    b.Navigation("ConfiguracionesUsuario");

                    b.Navigation("EstadisticasMensuales");

                    b.Navigation("MensajesContactos");

                    b.Navigation("MetasAhorros");

                    b.Navigation("Reportes");

                    b.Navigation("Sesiones");

                    b.Navigation("Templates");

                    b.Navigation("Transacciones");
                });
#pragma warning restore 612, 618
        }
    }
}
