// <auto-generated />
using System;
using HoneyBack.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HoneyBack.Migrations
{
    [DbContext(typeof(HoneyBalanceDbContext))]
    partial class HoneyBalanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HoneyBack.Models.ConfiguracionesUsuario", b =>
                {
                    b.Property<int>("ConfiguracionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ConfiguracionID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConfiguracionId"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("AvatarURL");

                    b.Property<string>("ConfiguracionPersonalizada")
                        .HasColumnType("text");

                    b.Property<bool?>("EsVeterano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FormatoFecha")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("DD/MM/YYYY");

                    b.Property<string>("Idioma")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("es");

                    b.Property<string>("MonedaPreferida")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("COP");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("NotificacionesEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool?>("NotificacionesPush")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool?>("PrimeraVez")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Tema")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("dark");

                    b.Property<string>("Timezone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("America/Bogota");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioID");

                    b.HasKey("ConfiguracionId")
                        .HasName("PK__Configur__9B95E0564150AC51");

                    b.HasIndex(new[] { "UsuarioId" }, "IDX_Configuraciones_Usuario");

                    b.HasIndex(new[] { "UsuarioId" }, "UQ__Configur__2B3DE7994E97C4E8")
                        .IsUnique();

                    b.ToTable("ConfiguracionesUsuario", (string)null);
                });

            modelBuilder.Entity("HoneyBack.Models.EntornoPersonal", b =>
                {
                    b.Property<int>("EntornoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("EntornoID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntornoId"));

                    b.Property<string>("DatosJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Etiqueta")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModuloClave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subtitulo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioID");

                    b.Property<string>("ValorPrincipal")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("EntornoId")
                        .HasName("PK_EntornosPersonales");

                    b.HasIndex(new[] { "UsuarioId", "ModuloClave" }, "IDX_Entornos_Usuario_Modulo");

                    b.ToTable("EntornosPersonales", (string)null);
                });

            modelBuilder.Entity("HoneyBack.Models.MensajesContacto", b =>
                {
                    b.Property<int>("ContactoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ContactoID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContactoId"));

                    b.Property<string>("Asunto")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FechaEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("FechaLeido")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("Leido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Respuesta")
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioID");

                    b.HasKey("ContactoId")
                        .HasName("PK__Mensajes__8E0F85C84F21B9E0");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MensajesContacto", (string)null);
                });

            modelBuilder.Entity("HoneyBack.Models.MetasAhorro", b =>
                {
                    b.Property<int>("MetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MetaID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MetaId"));

                    b.Property<bool?>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("otro");

                    b.Property<string>("Color")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("#FFD8A9");

                    b.Property<bool?>("Completada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCompletada")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<DateOnly?>("FechaObjetivo")
                        .HasColumnType("date");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("MontoActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("MontoObjetivo")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Prioridad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioID");

                    b.HasKey("MetaId")
                        .HasName("PK__MetasAho__60EE57F83C03D1E5");

                    b.HasIndex(new[] { "Activa" }, "IDX_Metas_Activa");

                    b.HasIndex(new[] { "Prioridad" }, "IDX_Metas_Prioridad")
                        .IsDescending();

                    b.HasIndex(new[] { "UsuarioId" }, "IDX_Metas_Usuario");

                    b.ToTable("MetasAhorro", (string)null);
                });

            modelBuilder.Entity("HoneyBack.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TokenID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character(6)")
                        .IsFixedLength();

                    b.Property<bool>("Used")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioID");

                    b.HasKey("TokenId")
                        .HasName("PK_PasswordResetTokens");

                    b.HasIndex(new[] { "UsuarioId", "Used", "ExpiresAtUtc" }, "IDX_PasswordResetTokens_Active");

                    b.HasIndex(new[] { "Token" }, "IDX_PasswordResetTokens_Token");

                    b.HasIndex(new[] { "UsuarioId" }, "IDX_PasswordResetTokens_Usuario");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("HoneyBack.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UsuarioId", "IsRevoked", "ExpiresAt" }, "IDX_RefreshTokens_Active");

                    b.HasIndex(new[] { "Token" }, "IDX_RefreshTokens_Token")
                        .IsUnique();

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("HoneyBack.Models.Sesione", b =>
                {
                    b.Property<long>("SesionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SesionID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SesionId"));

                    b.Property<bool?>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("IPAddress");

                    b.Property<string>("TokenSesion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioID");

                    b.HasKey("SesionId")
                        .HasName("PK__Sesiones__52FD7C0689AF3185");

                    b.HasIndex("UsuarioId");

                    b.HasIndex(new[] { "TokenSesion" }, "UQ__Sesiones__567B1115B8F65C64")
                        .IsUnique();

                    b.ToTable("Sesiones");
                });

            modelBuilder.Entity("HoneyBack.Models.Transaccione", b =>
                {
                    b.Property<int>("TransaccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TransaccionID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransaccionId"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioID");

                    b.HasKey("TransaccionId")
                        .HasName("PK_Transacciones");

                    b.HasIndex(new[] { "Fecha" }, "IDX_Transacciones_Fecha");

                    b.HasIndex(new[] { "Tipo" }, "IDX_Transacciones_Tipo");

                    b.HasIndex(new[] { "UsuarioId" }, "IDX_Transacciones_Usuario");

                    b.ToTable("Transacciones", (string)null);
                });

            modelBuilder.Entity("HoneyBack.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("AvatarURL");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PreferenciasMoneda")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("COP");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("UsuarioId")
                        .HasName("PK__Usuarios__2B3DE7981B407AB9");

                    b.HasIndex(new[] { "Email" }, "UQ__Usuarios__A9D10534C1437617")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("HoneyBack.Models.ConfiguracionesUsuario", b =>
                {
                    b.HasOne("HoneyBack.Models.Usuario", "Usuario")
                        .WithOne("ConfiguracionesUsuario")
                        .HasForeignKey("HoneyBack.Models.ConfiguracionesUsuario", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Configuraciones_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HoneyBack.Models.EntornoPersonal", b =>
                {
                    b.HasOne("HoneyBack.Models.Usuario", "Usuario")
                        .WithMany("EntornosPersonales")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EntornosPersonales_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HoneyBack.Models.MensajesContacto", b =>
                {
                    b.HasOne("HoneyBack.Models.Usuario", "Usuario")
                        .WithMany("MensajesContactos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_MensajesContacto_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HoneyBack.Models.MetasAhorro", b =>
                {
                    b.HasOne("HoneyBack.Models.Usuario", "Usuario")
                        .WithMany("MetasAhorros")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Metas_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HoneyBack.Models.PasswordResetToken", b =>
                {
                    b.HasOne("HoneyBack.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PasswordResetTokens_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HoneyBack.Models.RefreshToken", b =>
                {
                    b.HasOne("HoneyBack.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HoneyBack.Models.Sesione", b =>
                {
                    b.HasOne("HoneyBack.Models.Usuario", "Usuario")
                        .WithMany("Sesiones")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Sesiones_UsuarioID");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HoneyBack.Models.Transaccione", b =>
                {
                    b.HasOne("HoneyBack.Models.Usuario", "Usuario")
                        .WithMany("Transacciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Transacciones_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HoneyBack.Models.Usuario", b =>
                {
                    b.Navigation("ConfiguracionesUsuario");

                    b.Navigation("EntornosPersonales");

                    b.Navigation("MensajesContactos");

                    b.Navigation("MetasAhorros");

                    b.Navigation("Sesiones");

                    b.Navigation("Transacciones");
                });
#pragma warning restore 612, 618
        }
    }
}
